### ISSUE TITLE
Case studies review

### ISSUE THREAD

**Issue by arobillard** [arobillard/portfolio-2018#1]
Hi @thomasjbradley ,

Any chance you have time to go over my case study pages and give me some feedback this week? Looking to get everything good to go for Adobe MAX next week.

https://arobillard.github.io/portfolio/

Thanks for all the help so far!

**Comment by thomasjbradley** [comment]
Sure I’ll look over them in the next couple days.

**Comment by thomasjbradley** [comment]
They all look really great.

- I’m a little unsure of not having your name at the top of the case study pages.
- The `<title>` tag needs to change for each of the pages for a11y & SEO reasons.

### Top table

- I really don’t like the "click here": what about linking that whole sentence
- Under visual design, there’s a typo: “the conpetitive analysis”
