### ISSUE TITLE
Interactive Wireframe Critique

### ISSUE THREAD

**Issue by zhaojanelle** [arobillard/portfolio-2018#4]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Creativeness** | Bland, boring | Fairly generic, but the colours are nice | **Good, works very well and is unique enough** | Wow! I never would have thought that would work so well! |
| **Effectiveness** | I don’t know what this is trying to do | The message isn’t completely clear and it’s difficult to use | It’s obvious and simple to use | **The project is super effective and easy to use** |
| **Quality** | Non-existent | Acceptable quality, more work could be done | Good quality, up to the expectations of the teacher | **Stunning quality, this person rocks!** |
| **Effort** | Zero effort, incomplete | Decent amount of effort | Goodly amount of effort that shows | **Amazing, over-the-top amount of effort** |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | **Well indented, fully valid, good semantics** |

A very well thought out website, with extra details that make it come alive, such as the animations. I really like how when you hover over the menu items, a related image appears. The case study pages are also very well laid out. My suggestion for improvement would be increasing the speed of some of the animations as well the direction from which they pop up. I notice on the case study page, the images all pop out from the left, try having it pop up from the bottom too. Also i think the drop shadows can be more feathered out. Overall, a very impressive portfolio website.

**Comment by arobillard** [comment]
Thanks for the feedback!
